# Generated by Django 4.2.4 on 2023-08-11 10:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=511, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=511, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=511, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Description', 'Description'), ('Address', 'Address'), ('Phone number', 'Phone number'), ('Email', 'Email'), ('Web site', 'Web site')], max_length=127, null=True, verbose_name='Turi')),
                ('icon', models.CharField(blank=True, max_length=63, null=True, verbose_name='Ikonka klas nomi')),
                ('data', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=511, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=511, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=511, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=31, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=31, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=31, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=511, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=511, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=511, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=511, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=511, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=511, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=31, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=31, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=31, null=True)),
                ('icon', models.CharField(blank=True, max_length=63, null=True, verbose_name='Ikonka klas nomi')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Manzil')),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=31, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=31, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=31, null=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Manzil')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=63, null=True, verbose_name='Ikonka klas nomi')),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_attachment', to='core.info')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment_AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=31, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=31, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=31, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_attachment', to='core.aboutus')),
            ],
        ),
    ]
